### ISSUE TITLE
Separators and fill don't work well together

### ISSUE THREAD

**Issue by devjgm** [coriolinus/num-runtime-fmt#3]
Thanks for this crate. It looks helpful. I'm trying to use it to format some numbers in a nicely readable way and I'm noticing that separators and fill don't seem to play nicely together. For example, I expected the following to be true:

```rust
assert_eq!("0000_0042", NumFmt::from_str("08_4")?.fmt(42)?);
```
However, the assertion fails:
```rust
thread 'main' panicked at src/main.rs:80:5:
assertion `left == right` failed
  left: "0000_0042"
 right: "000_0042"
```

---
I added the following patch to your code to verify this, and this also fails:

```diff
diff --git a/tests/format.rs b/tests/format.rs
index d2c7bf1..b7a395a 100644
--- a/tests/format.rs
+++ b/tests/format.rs
@@ -192,6 +192,8 @@ test_mod! { separator:
     space_float(" ", 123456789.0, "123 456 789");
     under_float("_", 123456789.0, "123_456_789");
 
+    with_fill("08_4", 42, "0000_0042");
+
     // TODO: do we _want_ post-decimal commas? Those feel weird to me somehow.
     only_pre_decimal(".9,", 123456789.87654321, "123,456,789.876543210");
 }
```
with the error:

```
test separator::with_fill ... FAILED

failures:

---- separator::with_fill stdout ----
[tests/format.rs:185] &fmt = NumFmt {
    fill: Some(
        '0',
    ),
    align: Right,
    sign: OnlyMinus,
    hash: false,
    zero: true,
    width: 8,
    precision: None,
    base: Decimal,
    separator: Some(
        '_',
    ),
    spacing: Some(
        4,
    ),
    decimal_separator: None,
}
thread 'separator::with_fill' panicked at tests/format.rs:185:1:
assertion `left == right` failed
  left: "000_0042"
 right: "0000_0042"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    separator::with_fill

test result: FAILED. 119 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

Are my expectations wrong about how this should work?

**Comment by coriolinus** [comment]
There's a reasonable argument to be made for each of two different, mutually exclusive behaviors:

- Width and fill combine such that width describes the total output width, including spacing characters.
- Width and fill combine such that width describes the numeric output width, excluding spacing characters.

Ultimately I implemented the former behavior because it is very explicit about how many characters you end up with; you can see this from an existing test case: https://github.com/coriolinus/num-runtime-fmt/blob/9ae5b781b5655c06a19f6496bbe507e64651cc21/tests/format.rs#L174

I do not intend to change this behavior.
